# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c23c41658c1fbbf89918d89695015759604cdfb359fcd9eaa2e52094264ffbcf89684c3eb447e24df011df8388db0f07020cdad6916943c0a963b51c7ffb8578

test:
  secret_key_base: f4dba1843b84257ebf343527a2adcb5a79d2cab0c50b18b5e10dfbe0947b180775622dc681395abf435e4dba15fe2aa8d92301bf6137d8cedad02a695d6acc15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
